### ISSUE TITLE
Platform Exception Error 

### ISSUE THREAD

**Issue by reshaud** [hoanglm4/flutter_youtube_view#10]
I am trying to setup your library and receive the following error 

Here is my code 

```

import 'dart:ui';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter_youtube_view/flutter_youtube_view.dart';
import 'package:flutter/material.dart';
import 'dart:core';

import data/movies.dart';

class DetailsPage extends StatefulWidget{
  final Movies record;

  //receive data from main.dart
  DetailsPage({Key key, @required this.record}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return _DetailsPageState();
  }
}

class _DetailsPageState extends State<DetailsPage> implements YouTubePlayerListener{
  FlutterYoutubeViewController _controller;
  double _currentVideoSecond = 0.0;
  String _playerState = "";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: <Widget>[
          Stack(
            children: <Widget>[
              Container(
                height: 360.0,
                width: double.infinity,
                child: _backgroundImage(widget.record),
              ),
              Container(
                  height: 360.0,
                  width: double.infinity,
                  color: Colors.black.withOpacity(0.375)),
              IconButton(
                  icon: Icon(
                    Icons.arrow_back,
                    color: Colors.white,
                  ),
                  onPressed: () => Navigator.pop(context)),
            ],
          ),
          Container(
              margin: EdgeInsets.only(top: 8.0,left: 8.0),
              child: Text('Plot Summary',
                style: TextStyle(fontSize: 20.0,
                    fontWeight: FontWeight.bold),
              )
          ),
          _aboutTitle(context, widget.record),
          Container(
            width: 200,
            height: 200,
            child: FlutterYoutubeView(
              onViewCreated: _onYoutubeCreated,
              listener: this,
              scaleMode: YoutubeScaleMode.none,
              params: YoutubeParam(
                videoId: widget.record.trailerUrl,
                showUI: false,
                startSeconds: 0.0
              ),
            ),
          ),
        ],
      ),
    );
  }

  //Youtube Methods Start
  @override
  void onCurrentSecond(double second) {
    print("onCurrentSecond second = $second");
    _currentVideoSecond = second;
  }

  @override
  void onError(String error) {
    print("onError error = $error");
  }

  @override
  void onReady() {
    print("onReady");
  }

  @override
  void onStateChange(String state) {
    print("onStateChange state = $state");
    setState(() {
      _playerState = state;
    });
  }

  @override
  void onVideoDuration(double duration) {
    print("onVideoDuration duration = $duration");
  }

  void _onYoutubeCreated(FlutterYoutubeViewController controller) {
    this._controller = controller;
  }
  //Youtube Methods End
}
```

This is what comes up in my console

```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,814ms.
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
I/chatty  (21355): uid=10083(u0_a83) 1.gpu identical 17 lines
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
I/chatty  (21355): uid=10083(u0_a83) 1.gpu identical 558 lines
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
E/flutter (21355): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Trying to create a platform view of unregistered type: plugins.hoanglm.com/youtube, null)
E/flutter (21355): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (21355): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (21355): <asynchronous suspension>
E/flutter (21355): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:580:54)
E/flutter (21355): <asynchronous suspension>
E/flutter (21355): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:505:14)
E/flutter (21355): <asynchronous suspension>
E/flutter (21355): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:178:29)
E/flutter (21355): <asynchronous suspension>
E/flutter (21355): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:159:5)
E/flutter (21355): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1617:9)
E/flutter (21355): #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (21355): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #13     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:413:13)
E/flutter (21355): #14     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
E/flutter (21355): #15     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
E/flutter (21355): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
E/flutter (21355): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
E/flutter (21355): #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
E/flutter (21355): #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
E/flutter (21355): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
E/flutter (21355): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (21355): #36     Render
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
I/chatty  (21355): uid=10083(u0_a83) 1.gpu identical 2 lines
D/EGL_emulation(21355): eglMakeCurrent: 0x9e36efe0: ver 2 0 (tinfo 0xa0d03280)
```

Any help is appreciated

**Comment by hoanglm4** [comment]
Hello @reshaud 
Please add the output of flutter doctor -v.
What flutter_youtube_view version are you using (check pubspec.lock)

**Comment by reshaud** [comment]
Hey @hoanglm4 

flutter_youtube_view version from pubspec.lock

```
  flutter_youtube_view:
    dependency: "direct main"
    description:
      name: flutter_youtube_view
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
```

Here is the flutter doctor -v output 

```
D:\Flutter Projects\cinema_app>flutter doctor -v
[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.3.8 at D:\flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

I received a new error from gradle today that i am  now looking into, see below 

```
C:\Users\Reshaud Ally\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.2.aar\4d28d6755ae211c97631a5e2cc44a346\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
D:\Flutter Projects\cinema_app\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\Users\Reshaud Ally\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.2.aar\4d28d6755ae211c97631a5e2cc44a346\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\Users\Reshaud Ally\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.2.aar\4d28d6755ae211c97631a5e2cc44a346\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/ttcIndex not found.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1


```

**Comment by hoanglm4** [comment]
Hello @reshaud 
Please show the build.gradle in android/app/build.gradle

**Comment by reshaud** [comment]
Hey @hoanglm4 

See build gradle file. Note i updated the minimum sdk and target versions a couple minutes ago to 21 and 28 respectively 

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.logicslide.cinemaapp"
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.android.support:multidex:1.0.3'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by reshaud** [comment]
Hey @hoanglm4 

here is a link to the project that may be more helpful 

[https://drive.google.com/file/d/1MgilFhAG3KeVfSRt05Vu6XYGBaTEfvTy/view?usp=sharing](url)

**Comment by reshaud** [comment]
Hey @hoanglm4 

 I got it fixed, the issue came from the gradle I followed these steps in the link below to fix

[https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility](url)
