### ISSUE TITLE
Full Screen and Youtube selections (like open with Youtube) not working on Android

### ISSUE THREAD

**Issue by malibayram** [hoanglm4/flutter_youtube_view#29]
when i click to fullscreen button nothing done but when i click to open with Youtube button i see this error

`
D/AndroidRuntime(10300): Shutting down VM
E/AndroidRuntime(10300): FATAL EXCEPTION: main
E/AndroidRuntime(10300): Process: dershub.senv2yayin, PID: 10300
E/AndroidRuntime(10300): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime(10300): 	at android.app.ContextImpl.startActivity(ContextImpl.java:682)
E/AndroidRuntime(10300): 	at android.app.ContextImpl.startActivity(ContextImpl.java:669)
E/AndroidRuntime(10300): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
E/AndroidRuntime(10300): 	at com.pierfrancescosoffritti.androidyoutubeplayer.core.ui.DefaultPlayerUiController$onVideoId$1.onClick(DefaultPlayerUiController.kt:283)
E/AndroidRuntime(10300): 	at android.view.View.performClick(View.java:5215)
E/AndroidRuntime(10300): 	at android.view.View$PerformClick.run(View.java:21193)
E/AndroidRuntime(10300): 	at android.os.Handler.handleCallback(Handler.java:742)
E/AndroidRuntime(10300): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10300): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(10300): 	at android.app.ActivityThread.main(ActivityThread.java:5653)
E/AndroidRuntime(10300): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10300): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
E/AndroidRuntime(10300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
I/Process (10300): Sending signal. PID: 10300 SIG: 9
Lost connection to device.
`

**Comment by SayaGames** [comment]
I have same issue for a long time. Resolution seems not to be fixed... I hide the showYoutube and showFullScreen buttons in params: YoutubeParams(). Then I will use Stack() to put my own fullscreen codes by scaling the video. 
`                      params: YoutubeParam(
                        videoId: video.url,
                        showUI: true,
                        startSeconds: 0.0,
                        autoPlay: true,
                        showYoutube: false,
                        showFullScreen: false,
                      )`

Did you find any solution?@malibayram91

**Comment by Shajeel-Afzal** [comment]
Full-Screen Video Playback is not possible with this library. It goes to the full screen but it does not rotate the video.

**Comment by Rohithgilla12** [comment]
@SayaGames How do you achieve it?
Can you please provide any code snippet?
Thanks
