### ISSUE TITLE
Android Instructions

### ISSUE THREAD

**Issue by Rohithgilla12** [hoanglm4/flutter_youtube_view#67]
Are there any android instructions on integrating the package?

I was able to make it work for iOS but on android is just closes when I open this view.

Logs before the crash

```W/Gralloc4(29124): allocator 3.x is not supported
W/Gralloc3(29124): allocator 3.x is not supported
D/FlutterYoutubeView(29124): params = {showYoutube=true, showFullScreen=false, startSeconds=0.0, scale_mode=0, videoId=ii_7IbHFEhc, showUI=true, autoPlay=true}
I/DecorView(29124): [INFO] isPopOver=false, config=false
I/DecorView(29124): updateCaptionType >> DecorView@adfbb0[], isFloating=false, isApplication=false, hasWindowDecorCaption=false, hasWindowControllerCallback=false
D/DecorView(29124): setCaptionType = 0, this = DecorView@adfbb0[]
D/InputTransport(29124): Input channel constructed: 'ea71c91', fd=213
I/ViewRootImpl@721baba[MainActivity](29124): setView = com.android.internal.policy.DecorView@adfbb0 TM=true
E/AndroidRuntime(29124): FATAL EXCEPTION: main
E/AndroidRuntime(29124): Process: io.with, PID: 29124
E/AndroidRuntime(29124): java.lang.AbstractMethodError: abstract method "void io.flutter.plugin.platform.PlatformView.onFlutterViewAttached(android.view.View)"
E/AndroidRuntime(29124): 	at io.flutter.plugin.platform.VirtualDisplayController.onFlutterViewAttached(VirtualDisplayController.java:181)
E/AndroidRuntime(29124): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:233)
E/AndroidRuntime(29124): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/AndroidRuntime(29124): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(29124): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(29124): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(29124): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AndroidRuntime(29124): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(29124): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(29124): 	at android.os.Looper.loop(Looper.java:206)

```

**Comment by Rohithgilla12** [comment]
In `gradle.properties` file add the following line

`android.enableDexingArtifactTransform=false`

it solves it

Thanks and closing the issue
